services:
  postgresql:
    container_name: postgresql
    #command: postgres -c 'max_connections=20'
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    healthcheck:
      test: "EXIT 0"
    logging:
      options:
        max-size: 10m
        max-file: "13"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - zipkin
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: unless-stopped
    ports:
      - "8020:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins
    logging:
      options:
        max-size: 10m
        max-file: "13"

networks:
  postgres:
    driver: bridge
  zipkin:
    driver: bridge
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
  postgres:
