spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

# Enable all endpoints
management:
  endpoint:
    health:
      show-details: always
      roles: ADMIN
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
