eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

server:
  port: 8081
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/products/**
        - id: carts
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/carts/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8050/realms/online-shop


management:
  endpoint:
    health:
      show-details: always
      roles: ADMIN
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  tracing:
    sampling:
      probability: 1.0
