eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/products/**
        - id: carts
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/carts/**

management:
  tracing:
    sampling:
      probability: 1.0
