eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

# Server Configuration
server:
  port: 8090

application:
  config:
    carts-url: http://localhost:8070/api/v1/carts

spring:
  application:
    name: product-service
  # Aspect Logging Configuration
  aop:
    auto: true

  # DataSource Configuration for PostgreSQL DB
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Liquibase Configuration
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    drop-first: false
    enabled: true
    default-schema: public

  #Docker compose configs
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

# Enable all endpoints
management:
  endpoint:
    health:
      show-details: always
      roles: ADMIN
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

  # Factory annotation values
  #application: