# Server Configuration
server:
  port: 8083

spring:
  application:
    name: discovery
  config:
    import: optional:config-server:http://localhost:8082

# Enable all endpoints
management:
  endpoint:
    health:
      show-details: always
      roles: ADMIN
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

